databases:
  - name: sso_db_user
    databaseName: sso_db
    user: sso_db_user
services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: sso_db
       property: postgres://sso_db_user:LfkjNwLq2WQdUR7klI3AfHTOS3k1qgln@dpg-cec5h8cgqg4ap4aql2tg-a/sso_db
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50